[workspace]
members = ["ameon", "client", "server"]

[package]
name = "terminal-chat"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
clap = { version = "4.6.6", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
terminal-chat = { path = "." }
chrono = { version = "0.4.45", features = ["serde"] }

[dependencies]
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
ameon = { path = "./ameon" }
chrono = { workspace = true, features = ["serde"] }
deflate = "1.0.0"
inflate = "0.4.5"
